DROP TABLE IF EXISTS post_replies CASCADE;

CREATE TABLE post_replies (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  post_id INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  content VARCHAR(255)
);